% Author       : Le Minh Nhat - K22 HCMUT
% Faculty      : Electrical and Electronics Engineering
% Course       : Microwave Engineering - Semester 252
% Date modified: 27/09/2026

function cases = aim_load_cases()
    % ===== Benchmark antenna-load cases =====
    % Define six representative antenna impedances used to evaluate
    % the adaptive L-network under different mismatch conditions.
    %
    % nominalVSWR preserves the rounded benchmark labels. The exact VSWR
    % is calculated from each complex load impedance when required.

    %% ===== Load definitions =====
    names = {'A','B','C','D','E','F'};

    Z = { ...
        50+0j, ...
        200+0j, ...
        50+75j, ...
        50-75j, ...
        25+50j, ...
        25-50j};

    nominalVSWR = { ...
        1.0, ...
        4.0, ...
        4.0, ...
        4.0, ...
        4.3, ...
        4.3};

    description = { ...
        'Ideal antenna', ...
        'Purely resistive mismatch', ...
        'High inductive mismatch', ...
        'High capacitive mismatch', ...
        'Extreme inductive mismatch', ...
        'Extreme capacitive mismatch'};

    %% ===== Case structure =====
    cases = struct( ...
        'name',names, ...
        'Z',Z, ...
        'nominalVSWR',nominalVSWR, ...
        'description',description);
end