% Author       : Le Minh Nhat - K22 HCMUT
% Faculty      : Electrical and Electronics Engineering
% Course       : Microwave Engineering - Semester 252
% Date modified: 27/09/2026

function animate_smith_tracking(h, saveGif, gifPath)
    % ===== Adaptive impedance matching visualization =====
    % Animate the discrete capacitor tuning process toward the 50-ohm
    % matching target on the Smith chart.
    %
    % The figure also tracks the capacitor states, VSWR convergence, and
    % input impedance during the matching process.
    %
    % Note: The animation duration represents visualization playback time
    % only and does not represent the physical AIM counter clock.

    %% ===== Input settings =====
    if nargin < 2 || isempty(saveGif)
        saveGif = false;
    end

    if nargin < 3 || isempty(gifPath)
        root = fileparts(fileparts(mfilename('fullpath')));
        gifPath = fullfile(root,'pics','sim','smith_tracking.gif');
    end

    % Create the output directory when GIF export is enabled
    if saveGif
        outDir = fileparts(gifPath);

        if ~exist(outDir,'dir')
            mkdir(outDir);
        end
    end

    %% ===== Animation settings =====
    animationDuration = 5.5;     % Moving portion [s]
    finalHold = 1.25;            % Final matched-state hold [s]

    % Limit the animation to approximately 180 frames for compact GIF size
    N = numel(h.step);
    stride = max(1,ceil(N/180));
    frameIdx = 1:stride:N;

    % Always include the exact final matching state
    if frameIdx(end) ~= N
        frameIdx(end+1) = N;
    end

    numFrames = numel(frameIdx);
    frameDelay = animationDuration/max(numFrames-1,1);
    frameDelay = max(frameDelay,0.02);

    %% ===== Figure initialization =====
    fig = figure( ...
        'Name','Adaptive Impedance Matching - Smith Tracking', ...
        'Color','w', ...
        'Position',[100 100 900 620]);

    t = tiledlayout(fig,2,2, ...
        'TileSpacing','compact', ...
        'Padding','compact');

    %% ===== Smith-chart tracking =====
    ax1 = nexttile(t,1);
    plot_smith_grid(ax1);
    hold(ax1,'on');

    % Initial antenna-load position
    gLoad = z_to_gamma(h.Zload,h.p.Z0);

    hLoad = plot(ax1, ...
        real(gLoad),imag(gLoad),'ks', ...
        'MarkerFaceColor','k', ...
        'MarkerSize',6, ...
        'LineWidth',1.0);

    % Perfect matching target: Gamma = 0 corresponds to 50 + j0 ohm
    hTarget = plot(ax1, ...
        0,0,'kx', ...
        'MarkerSize',9, ...
        'LineWidth',1.4);

    % Matching trajectory and current impedance position
    hPath = animatedline(ax1, ...
        'Color','k', ...
        'LineStyle','-', ...
        'LineWidth',1.3);

    hNow = plot(ax1, ...
        NaN,NaN,'ko', ...
        'MarkerFaceColor','w', ...
        'MarkerSize',6, ...
        'LineWidth',1.1);

    legend(ax1, ...
        [hLoad hTarget hPath hNow], ...
        {'Load','50-\Omega target','Trajectory','Current'}, ...
        'Location','southoutside', ...
        'Orientation','horizontal', ...
        'Box','off', ...
        'FontSize',8);

    title(ax1,'(a) Smith-chart tracking', ...
        'FontWeight','normal');

    %% ===== Capacitor tuning =====
    ax2 = nexttile(t,2);
    hold(ax2,'on');

    % Solid and dashed lines distinguish the two DTC branches
    hCp = animatedline(ax2, ...
        'Color','k', ...
        'LineStyle','-', ...
        'LineWidth',1.2);

    hCs = animatedline(ax2, ...
        'Color','k', ...
        'LineStyle','--', ...
        'LineWidth',1.2);

    xlabel(ax2,'Counter update');
    ylabel(ax2,'Capacitance (pF)');

    legend(ax2, ...
        [hCp hCs], ...
        {'C_{PAR}','C_{SERIES}'}, ...
        'Location','northeast', ...
        'Box','off', ...
        'FontSize',8);

    title(ax2,'(b) Capacitor tuning', ...
        'FontWeight','normal');

    grid(ax2,'on');

    % Fix the axes before animation to prevent dynamic rescaling
    xlim(ax2,[h.step(1) h.step(end)]);

    capAll = [h.Cpar(:)*1e12; h.Cseries(:)*1e12];
    capMin = min(capAll);
    capMax = max(capAll);
    capMargin = max(0.25,0.08*(capMax-capMin));

    ylim(ax2,[capMin-capMargin capMax+capMargin]);

    %% ===== VSWR convergence =====
    ax3 = nexttile(t,3);
    hold(ax3,'on');

    hV = animatedline(ax3, ...
        'Color','k', ...
        'LineStyle','-', ...
        'LineWidth',1.2);

    % VSWR = 1.5 is shown as a practical matching reference
    yline(ax3, ...
        1.5,'k--','VSWR = 1.5', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    xlabel(ax3,'Counter update');
    ylabel(ax3,'VSWR');

    title(ax3,'(c) VSWR convergence', ...
        'FontWeight','normal');

    grid(ax3,'on');

    xlim(ax3,[h.step(1) h.step(end)]);

    vswrMax = max(h.VSWR);
    ylim(ax3,[1 max(1.6,1.08*vswrMax)]);

    %% ===== Input impedance =====
    ax4 = nexttile(t,4);
    hold(ax4,'on');

    % Real and imaginary parts of the transformed input impedance
    hR = animatedline(ax4, ...
        'Color','k', ...
        'LineStyle','-', ...
        'LineWidth',1.2);

    hX = animatedline(ax4, ...
        'Color','k', ...
        'LineStyle','--', ...
        'LineWidth',1.2);

    % Desired matching point: Zin = 50 + j0 ohm
    yline(ax4, ...
        50,'k:','R_{ref}=50 \Omega', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    yline(ax4, ...
        0,'k-.','X_{ref}=0', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    xlabel(ax4,'Counter update');
    ylabel(ax4,'Impedance (\Omega)');

    legend(ax4, ...
        [hR hX], ...
        {'Re\{Z_{in}\}','Im\{Z_{in}\}'}, ...
        'Location','northeast', ...
        'Box','off', ...
        'FontSize',8);

    title(ax4,'(d) Input impedance', ...
        'FontWeight','normal');

    grid(ax4,'on');

    % Fix the impedance axes using the complete simulated trajectory
    xlim(ax4,[h.step(1) h.step(end)]);

    zValues = [ ...
        real(h.Zin(:)); ...
        imag(h.Zin(:)); ...
        0; ...
        50];

    zMin = min(zValues);
    zMax = max(zValues);
    zMargin = max(5,0.08*(zMax-zMin));

    ylim(ax4,[zMin-zMargin zMax+zMargin]);

    %% ===== Figure style =====
    set([ax1 ax2 ax3 ax4], ...
        'FontName','Times New Roman', ...
        'FontSize',10, ...
        'LineWidth',0.8, ...
        'Box','on');

    ax2.GridAlpha = 0.12;
    ax3.GridAlpha = 0.12;
    ax4.GridAlpha = 0.12;

    %% ===== Animation loop =====
    for ii = 1:numFrames
        k = frameIdx(ii);

        % Update Smith-chart trajectory
        addpoints(hPath, ...
            real(h.Gamma(k)), ...
            imag(h.Gamma(k)));

        set(hNow, ...
            'XData',real(h.Gamma(k)), ...
            'YData',imag(h.Gamma(k)));

        % Update capacitor states
        addpoints(hCp,h.step(k),h.Cpar(k)*1e12);
        addpoints(hCs,h.step(k),h.Cseries(k)*1e12);

        % Update VSWR
        addpoints(hV,h.step(k),h.VSWR(k));

        % Update transformed input impedance
        addpoints(hR,h.step(k),real(h.Zin(k)));
        addpoints(hX,h.step(k),imag(h.Zin(k)));

        % Display the current matching state
        title(t, sprintf( ...
            ['Adaptive Impedance Matching | %.0f MHz | ' ...
             'step %d/%d | %s | ' ...
             'Z_{in}=%.2f%+.2fj \\Omega | VSWR=%.3f'], ...
            h.f/1e6, ...
            h.step(k), ...
            h.step(end), ...
            h.phase(k), ...
            real(h.Zin(k)), ...
            imag(h.Zin(k)), ...
            h.VSWR(k)), ...
            'FontName','Times New Roman', ...
            'FontSize',11, ...
            'FontWeight','normal');

        drawnow;

        %% ===== GIF export =====
        if saveGif
            frame = getframe(fig);
            im = frame2im(frame);
            [A,map] = rgb2ind(im,256);

            if ii == 1
                % First frame initializes the GIF
                imwrite(A,map,gifPath, ...
                    'gif', ...
                    'LoopCount',Inf, ...
                    'DelayTime',frameDelay);

            elseif ii == numFrames
                % Hold the final matched state before restarting the GIF
                imwrite(A,map,gifPath, ...
                    'gif', ...
                    'WriteMode','append', ...
                    'DelayTime',finalHold);

            else
                imwrite(A,map,gifPath, ...
                    'gif', ...
                    'WriteMode','append', ...
                    'DelayTime',frameDelay);
            end
        end

        % Control live MATLAB playback speed
        if ii < numFrames
            pause(frameDelay);
        else
            pause(finalHold);
        end
    end
end