% Author       : Le Minh Nhat - K22 HCMUT
% Faculty      : Electrical and Electronics Engineering
% Course       : Microwave Engineering - Semester 252
% Date modified: 27/09/2026

function D = plot_phase_sweep(f, VSWR, saveFigure)
    % ===== Constant-VSWR load-phase sweep =====
    % Sweep the phase of the load reflection coefficient along a
    % constant-VSWR circle and evaluate the adaptive L-network response.
    %
    % The results show the required capacitor values, insertion loss,
    % net gain, residual mismatch, and feasible matching region.

    %% ===== Input settings =====
    if nargin < 2 || isempty(VSWR)
        VSWR = 4.3;
    end

    if nargin < 3
        saveFigure = false;
    end

    p = aim_constants();

    %% ===== Load-phase sweep =====
    phaseDeg = (-180:1:180).';

    % Convert the specified VSWR to a constant reflection magnitude
    rho = (VSWR-1)/(VSWR+1);

    % Generate the complete constant-VSWR circle in the Gamma plane
    gamma = rho .* exp(1j*deg2rad(phaseDeg));
    Zload = gamma_to_z(gamma,p.Z0);

    N = numel(phaseDeg);

    Cpar      = nan(N,1);
    Cseries   = nan(N,1);
    IL        = nan(N,1);
    Gain      = nan(N,1);
    VSWRafter = nan(N,1);
    feasible  = false(N,1);

    % Evaluate the analytical matching solution at each load phase
    for k = 1:N
        sol = aim_closed_form(f,Zload(k),p,'auto');

        if sol.feasibleCaps
            r = aim_network_response( ...
                f,Zload(k), ...
                sol.Cpar,sol.Cseries,p);

            Cpar(k)      = sol.Cpar*1e12;
            Cseries(k)   = sol.Cseries*1e12;
            IL(k)        = r.IL;
            Gain(k)      = r.Gain;
            VSWRafter(k) = r.VSWRmatch;
            feasible(k)  = true;
        end
    end

    %% ===== Sweep data =====
    D = table( ...
        phaseDeg, ...
        real(Zload), ...
        imag(Zload), ...
        Cpar, ...
        Cseries, ...
        IL, ...
        Gain, ...
        VSWRafter, ...
        feasible, ...
        'VariableNames', ...
        {'PhaseGammaLoad_deg', ...
         'Rload_ohm', ...
         'Xload_ohm', ...
         'Cpar_pF', ...
         'Cseries_pF', ...
         'IL_dB', ...
         'Gain_dB', ...
         'VSWR_After', ...
         'Feasible'});

    %% ===== Figure initialization =====
    fig = figure( ...
        'Name','Phase GammaLoad sweep', ...
        'Color','w', ...
        'Position',[100 100 760 540]);

    t = tiledlayout(fig,2,2, ...
        'TileSpacing','compact', ...
        'Padding','compact');

    % Common monochrome figure style
    set(fig,'DefaultAxesFontName','Times New Roman');
    set(fig,'DefaultAxesFontSize',10);
    set(fig,'DefaultAxesLineWidth',0.8);
    set(fig,'DefaultLineLineWidth',1.2);

    %% ===== Insertion loss and net gain =====
    ax1 = nexttile(t,1);
    hold(ax1,'on');

    % IL: solid line with circle markers
    hIL = plot(ax1, ...
        phaseDeg,IL, ...
        'k-', ...
        'LineWidth',1.2, ...
        'Marker','o', ...
        'MarkerIndices',1:30:N, ...
        'MarkerSize',4, ...
        'MarkerFaceColor','w');

    % Net gain: dashed line with square markers
    hGain = plot(ax1, ...
        phaseDeg,Gain, ...
        'k--', ...
        'LineWidth',1.2, ...
        'Marker','s', ...
        'MarkerIndices',15:30:N, ...
        'MarkerSize',4, ...
        'MarkerFaceColor','w');

    yline(ax1,0,'k:', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    xlabel(ax1,'\angle\Gamma_L (deg)');
    ylabel(ax1,'Magnitude (dB)');

    legend(ax1, ...
        [hIL hGain], ...
        {'IL','G'}, ...
        'Location','best', ...
        'Box','off', ...
        'FontSize',8);

    title(ax1,'(a) Insertion loss and net gain', ...
        'FontWeight','normal');

    grid(ax1,'on');
    ax1.GridAlpha = 0.12;
    ax1.Box = 'on';

    xlim(ax1,[-180 180]);
    xticks(ax1,-180:60:180);

    %% ===== Required capacitances =====
    ax2 = nexttile(t,2);
    hold(ax2,'on');

    % Shunt capacitor
    hCpar = plot(ax2, ...
        phaseDeg,Cpar, ...
        'k-', ...
        'LineWidth',1.2, ...
        'Marker','o', ...
        'MarkerIndices',1:30:N, ...
        'MarkerSize',4, ...
        'MarkerFaceColor','w');

    % Series capacitor
    hCseries = plot(ax2, ...
        phaseDeg,Cseries, ...
        'k--', ...
        'LineWidth',1.2, ...
        'Marker','s', ...
        'MarkerIndices',15:30:N, ...
        'MarkerSize',4, ...
        'MarkerFaceColor','w');

    % Configured DTC tuning limits
    yline(ax2,p.Cmin*1e12,'k:', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    yline(ax2,p.Cmax*1e12,'k:', ...
        'LineWidth',0.8, ...
        'HandleVisibility','off');

    xlabel(ax2,'\angle\Gamma_L (deg)');
    ylabel(ax2,'Capacitance (pF)');

    legend(ax2, ...
        [hCpar hCseries], ...
        {'C_{PAR}','C_{SERIES}'}, ...
        'Location','best', ...
        'Box','off', ...
        'FontSize',8);

    title(ax2,'(b) Required capacitances', ...
        'FontWeight','normal');

    grid(ax2,'on');
    ax2.GridAlpha = 0.12;
    ax2.Box = 'on';

    xlim(ax2,[-180 180]);
    xticks(ax2,-180:60:180);

    %% ===== Residual mismatch =====
    ax3 = nexttile(t,3);
    hold(ax3,'on');

    plot(ax3, ...
        phaseDeg,VSWRafter, ...
        'k-', ...
        'LineWidth',1.2, ...
        'Marker','d', ...
        'MarkerIndices',1:30:N, ...
        'MarkerSize',4, ...
        'MarkerFaceColor','w');

    % Reference level used to visualize matching quality
    yline(ax3,1.5,'k--', ...
        'LineWidth',0.9, ...
        'HandleVisibility','off');

    xlabel(ax3,'\angle\Gamma_L (deg)');
    ylabel(ax3,'VSWR after matching');

    title(ax3,'(c) Residual mismatch', ...
        'FontWeight','normal');

    grid(ax3,'on');
    ax3.GridAlpha = 0.12;
    ax3.Box = 'on';

    xlim(ax3,[-180 180]);
    xticks(ax3,-180:60:180);

    %% ===== Constant-VSWR Smith chart =====
    ax4 = nexttile(t,4);
    hold(ax4,'on');

    plot_smith_grid(ax4);

    % Complete load circle corresponding to the specified VSWR
    hCircle = plot(ax4, ...
        real(gamma),imag(gamma), ...
        'k-', ...
        'LineWidth',1.2);

    % Mark a representative subset of feasible matching points
    idx = find(feasible);

    if ~isempty(idx)
        markerStep = max(1,round(numel(idx)/18));
        idxMarker = idx(1:markerStep:end);

        hFeasible = plot(ax4, ...
            real(gamma(idxMarker)), ...
            imag(gamma(idxMarker)), ...
            'ko', ...
            'LineStyle','none', ...
            'MarkerSize',4, ...
            'MarkerFaceColor','w');

        legend(ax4, ...
            [hCircle hFeasible], ...
            {sprintf('VSWR = %.1f',VSWR),'Feasible'}, ...
            'Location','southoutside', ...
            'Orientation','horizontal', ...
            'Box','off', ...
            'FontSize',8);
    else
        legend(ax4, ...
            hCircle, ...
            {sprintf('VSWR = %.1f',VSWR)}, ...
            'Location','southoutside', ...
            'Orientation','horizontal', ...
            'Box','off', ...
            'FontSize',8);
    end

    title(ax4,'(d) Constant-VSWR load circle', ...
        'FontWeight','normal');

    ax4.Box = 'on';

    %% ===== Figure title =====
    title(t, ...
        sprintf('Load-phase sweep at %.0f MHz',f/1e6), ...
        'FontName','Times New Roman', ...
        'FontSize',11, ...
        'FontWeight','normal');

    %% ===== Figure export =====
    if saveFigure
        root = fileparts(fileparts(mfilename('fullpath')));
        outDir = fullfile(root,'pics','sim');

        if ~exist(outDir,'dir')
            mkdir(outDir);
        end

        out = fullfile(outDir, ...
            sprintf('phase_sweep_%.0fMHz.png',f/1e6));

        exportgraphics(fig,out, ...
            'Resolution',400, ...
            'BackgroundColor','white');
    end
end